name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      name: Setup .NET
      with:
        dotnet-version: 6.0.x
        
    - uses: franzbischoff/replace_envs@v1
      name: Replace Tokens
      env:
        SHC_RAW: ${{ secrets.SHC_RAW }}

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Test SHC
      run: dotnet test .\Vacscan.Net.SHC.Test  --no-build --verbosity normal
